services:

  api:
    image: node
    working_dir: /api
    entrypoint: npm run $API_COMMAND
    restart: always
    environment:
      SECRET: $SECRET
      STRIPE_API_KEY: $STRIPE_API_KEY
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_USER: api_user
      MYSQL_HOST: db
      EMAIL: $EMAIL
      EMAIL_PASSWORD: $EMAIL_PASSWORD
      EMAIL_SERVICE: $EMAIL_SERVICE
      FRONTEND_ORIGIN: $FRONTEND_ORIGIN
    ports:
      - 8080:8080
    volumes:
      - ./api:/api
      - uploads:/uploads
    depends_on:
      - db

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_DATABASE: shop_stack
      MYSQL_USER: api_user
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    volumes:
      - data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d

volumes:
  data:
  uploads:
