services:

  api:
    image: node
    working_dir: /api
    entrypoint: npm start
    environment:
      STRIPE_API_KEY: $STRIPE_API_KEY
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    ports:
      - 8080:8080
    volumes:
      - ./api:/api
    depends_on:
      - db

  db:
    image: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_DATABASE: shop_stack
      MYSQL_USER: api_user
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d

volumes:
  data:
